// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/cluster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uptime        int64                  `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	CacheCount    int32                  `protobuf:"varint,3,opt,name=cache_count,json=cacheCount,proto3" json:"cache_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *HealthCheckResponse) GetCacheCount() int32 {
	if x != nil {
		return x.CacheCount
	}
	return 0
}

type InvalidateCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	OriginalNode  string                 `protobuf:"bytes,2,opt,name=original_node,json=originalNode,proto3" json:"original_node,omitempty"` // For preventing loops
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheRequest) Reset() {
	*x = InvalidateCacheRequest{}
	mi := &file_api_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheRequest) ProtoMessage() {}

func (x *InvalidateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *InvalidateCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InvalidateCacheRequest) GetOriginalNode() string {
	if x != nil {
		return x.OriginalNode
	}
	return ""
}

type InvalidateCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheResponse) Reset() {
	*x = InvalidateCacheResponse{}
	mi := &file_api_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheResponse) ProtoMessage() {}

func (x *InvalidateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheResponse.ProtoReflect.Descriptor instead.
func (*InvalidateCacheResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *InvalidateCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvalidateCacheResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CacheLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheLookupRequest) Reset() {
	*x = CacheLookupRequest{}
	mi := &file_api_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheLookupRequest) ProtoMessage() {}

func (x *CacheLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheLookupRequest.ProtoReflect.Descriptor instead.
func (*CacheLookupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *CacheLookupRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheLookupResponse) Reset() {
	*x = CacheLookupResponse{}
	mi := &file_api_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheLookupResponse) ProtoMessage() {}

func (x *CacheLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheLookupResponse.ProtoReflect.Descriptor instead.
func (*CacheLookupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *CacheLookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CacheLookupResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_api_proto_cluster_proto protoreflect.FileDescriptor

const file_api_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/cluster.proto\x12\acluster\"-\n" +
	"\x12HealthCheckRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"f\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\x03R\x06uptime\x12\x1f\n" +
	"\vcache_count\x18\x03 \x01(\x05R\n" +
	"cacheCount\"O\n" +
	"\x16InvalidateCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\roriginal_node\x18\x02 \x01(\tR\foriginalNode\"I\n" +
	"\x17InvalidateCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x12CacheLookupRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"E\n" +
	"\x13CacheLookupResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2\xfa\x01\n" +
	"\x0eClusterService\x12H\n" +
	"\vHealthCheck\x12\x1b.cluster.HealthCheckRequest\x1a\x1c.cluster.HealthCheckResponse\x12T\n" +
	"\x0fInvalidateCache\x12\x1f.cluster.InvalidateCacheRequest\x1a .cluster.InvalidateCacheResponse\x12H\n" +
	"\vCacheLookup\x12\x1b.cluster.CacheLookupRequest\x1a\x1c.cluster.CacheLookupResponseB-Z+github.com/afterdarksys/apiproxyd/api/protob\x06proto3"

var (
	file_api_proto_cluster_proto_rawDescOnce sync.Once
	file_api_proto_cluster_proto_rawDescData []byte
)

func file_api_proto_cluster_proto_rawDescGZIP() []byte {
	file_api_proto_cluster_proto_rawDescOnce.Do(func() {
		file_api_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cluster_proto_rawDesc), len(file_api_proto_cluster_proto_rawDesc)))
	})
	return file_api_proto_cluster_proto_rawDescData
}

var file_api_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_cluster_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),      // 0: cluster.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 1: cluster.HealthCheckResponse
	(*InvalidateCacheRequest)(nil),  // 2: cluster.InvalidateCacheRequest
	(*InvalidateCacheResponse)(nil), // 3: cluster.InvalidateCacheResponse
	(*CacheLookupRequest)(nil),      // 4: cluster.CacheLookupRequest
	(*CacheLookupResponse)(nil),     // 5: cluster.CacheLookupResponse
}
var file_api_proto_cluster_proto_depIdxs = []int32{
	0, // 0: cluster.ClusterService.HealthCheck:input_type -> cluster.HealthCheckRequest
	2, // 1: cluster.ClusterService.InvalidateCache:input_type -> cluster.InvalidateCacheRequest
	4, // 2: cluster.ClusterService.CacheLookup:input_type -> cluster.CacheLookupRequest
	1, // 3: cluster.ClusterService.HealthCheck:output_type -> cluster.HealthCheckResponse
	3, // 4: cluster.ClusterService.InvalidateCache:output_type -> cluster.InvalidateCacheResponse
	5, // 5: cluster.ClusterService.CacheLookup:output_type -> cluster.CacheLookupResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cluster_proto_init() }
func file_api_proto_cluster_proto_init() {
	if File_api_proto_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cluster_proto_rawDesc), len(file_api_proto_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cluster_proto_goTypes,
		DependencyIndexes: file_api_proto_cluster_proto_depIdxs,
		MessageInfos:      file_api_proto_cluster_proto_msgTypes,
	}.Build()
	File_api_proto_cluster_proto = out.File
	file_api_proto_cluster_proto_goTypes = nil
	file_api_proto_cluster_proto_depIdxs = nil
}
